

steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/pkdeltaai-05/gcp-devops-project", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/pkdeltaai-05/gcp-devops-project"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/pkdeltaai-05/gcp-devops-project
  - --location=us-central1
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod

options:
  logging: CLOUD_LOGGING_ONLY





#The below script works, commenting it for trying other options
# steps:
# - name: 'docker'
#   args: ['build', '-t', 'gcr.io/pkdeltaai-05/gcp-devops-project', '.']
# images: 
# - 'gcr.io/pkdeltaai-05/gcp-devops-project'
# options:
#  logging: CLOUD_LOGGING_ONLY



#Not working some issue, it is not able to find the image.  It is for artifact registry 

# steps:
# - name: 'docker'
#   args: ['build', '-t', 'europe-west4-docker.pkg.dev/pkdeltaai-05/gcp-devops-project/myimage', '.']
# logsBucket: 'gs://pkdeltaai-05-build-logs-bucket'
# images: 
# - 'europe-west4-docker.pkg.dev/pkdeltaai-05/gcp-devops-project/myimage'
# options:
#  logging: GCS_ONLY