steps:
- name: 'docker'
  args: ['build', '-t', 'eu.gcr.io/pkdeltaai-05/gcp-devops-project', '.']
logsBucket: 'gs://pkdeltaai-05-build-logs-bucket'
images: 
- 'eu.gcr.io/pkdeltaai-05/gcp-devops-project/gcp-devops-project'
options:
 logging: GCS_ONLY




# steps:
# - name: 'docker'
#   args: ['build', '-t', 'gcr.io/pkdeltaai-05/gcp-devops-project', '.']
# images: 
# - 'gcr.io/pkdeltaai-05/gcp-devops-project'
# options:
#  logging: CLOUD_LOGGING_ONLY
